In [16]:
import pandas as pd
import seaborn as sns
import pylab as pl
import matplotlib.pyplot as plt
import numpy as np

In [2]:
data_dir = "../Lucas_Cecile/"

In [3]:
data = pd.read_excel(data_dir+"PST_databrutes.xlsx")

In [4]:
data

,Observation id,Subject,Species,Session,Phase,Phase_session,PST condition,Behavior,Modifier #1,Observation date,Observation duration,Observation type,Media duration (s),coder,Date,Behavioral category,Modifier #2,Behavior type,Time
0,AMI_03-02-2026_2_H_L.MTS,Amidala,Macaca_mulatta,1,Habituation,1,Transparent,D2,Success,2026-04-17 09:14:18.077,80.36,Media file(s),154.30,Lucas,03.02.2026,PST,NaN,POINT,13.28
1,AMI_03-02-2026_2_H_L.MTS,Amidala,Macaca_mulatta,1,Habituation,1,Transparent,E3,Success,2026-04-17 09:14:18.077,80.36,Media file(s),154.30,Lucas,03.02.2026,PST,NaN,POINT,17.32
2,AMI_03-02-2026_2_H_L.MTS,Amidala,Macaca_mulatta,1,Habituation,1,Transparent,E2,Success,2026-04-17 09:14:18.077,80.36,Media file(s),154.30,Lucas,03.02.2026,PST,NaN,POINT,20.88
3,AMI_03-02-2026_2_H_L.MTS,Amidala,Macaca_mulatta,1,Habituation,1,Transparent,In area,Djo,2026-04-17 09:14:18.077,80.36,Media file(s),154.30,Lucas,03.02.2026,Social,NaN,POINT,22.72
4,AMI_03-02-2026_2_H_L.MTS,Amidala,Macaca_mulatta,1,Habituation,1,Transparent,D5,Success,2026-04-17 09:14:18.077,80.36,Media file(s),154.30,Lucas,03.02.2026,PST,NaN,POINT,25.24
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5952,YIN_20-03-2026_2,Yin,Macaca_tonkeana,20,Post-test,5,Transparent,C1,Success,2026-05-04 00:20:48.148,62.06,Media file(s),97.92,Francis,20.03.2026,PST,NaN,POINT,34.76
5953,YIN_20-03-2026_2,Yin,Macaca_tonkeana,20,Post-test,5,Transparent,B1,Success,2026-05-04 00:20:48.148,62.06,Media file(s),97.92,Francis,20.03.2026,PST,NaN,POINT,36.36
5954,YIN_20-03-2026_2,Yin,Macaca_tonkeana,20,Post-test,5,Transparent,C3,Success,2026-05-04 00:20:48.148,62.06,Media file(s),97.92,Francis,20.03.2026,PST,NaN,POINT,38.50
5955,YIN_20-03-2026_2,Yin,Macaca_tonkeana,20,Post-test,5,Transparent,B4,Success,2026-05-04 00:20:48.148,62.06,Media file(s),97.92,Francis,20.03.2026,PST,NaN,POINT,40.22
5956,YIN_20-03-2026_2,Yin,Macaca_tonkeana,20,Post-test,5,Transparent,D5,Revisit,2026-05-04 00:20:48.148,62.06,Media file(s),97.92,Francis,20.03.2026,PST,NaN,POINT,41.74

In [39]:
columns_ref = np.array(['A','B','C','D','E'])
rows_ref = np.arange(1,6)

In [71]:
processed_data = pd.DataFrame()
for grp in data.groupby(['Subject','Session','Phase','Species']):
    print(grp[0])
#     print(grp[1])
    temp = pd.DataFrame()
    sub = grp[1].loc[(grp[1]['Modifier #1']=='Success')|(grp[1]['Modifier #1']=='Revisit')]
    coords = [[ rows_ref[np.where(rows_ref==int(x[1]))[0]]-1, np.where(columns_ref==x[0])[0] ]  for x in sub['Behavior'].values]
    rows = np.array(coords)[:,0].flatten()
    cols = np.array(coords)[:,1].flatten()
    
    temp['Behavior'] = sub['Behavior'].values
    temp['Phase_Session'] = sub['Phase_session'].values
    temp['Rows'] = rows
    temp['Cols'] = cols
    temp['Reward'] = [1 if x == 'Success' else 0 for x in sub['Modifier #1'].values]
    temp['Time'] = sub['Time'].values
    #temp['Species'] = sub['Species'].values
    temp['PST_condition'] = sub['PST condition'].values
    temp['Subject'] = grp[0][0]
    temp['Session'] = grp[0][1]
    temp['Phase'] = grp[0][2]
    temp['Species'] = grp[0][3]
    processed_data = pd.concat([processed_data,temp])

('Amidala', 1, 'Habituation', 'Macaca_mulatta')
('Amidala', 2, 'Habituation', 'Macaca_mulatta')
('Amidala', 3, 'Habituation', 'Macaca_mulatta')
('Amidala', 4, 'Habituation', 'Macaca_mulatta')
('Amidala', 5, 'Habituation', 'Macaca_mulatta')
('Amidala', 6, 'Test', 'Macaca_mulatta')
('Amidala', 7, 'Test', 'Macaca_mulatta')
('Amidala', 8, 'Test', 'Macaca_mulatta')
('Amidala', 9, 'Test', 'Macaca_mulatta')
('Amidala', 10, 'Test', 'Macaca_mulatta')
('Amidala', 11, 'Test', 'Macaca_mulatta')
('Amidala', 12, 'Test', 'Macaca_mulatta')
('Amidala', 13, 'Test', 'Macaca_mulatta')
('Amidala', 14, 'Test', 'Macaca_mulatta')
('Amidala', 15, 'Test', 'Macaca_mulatta')
('Amidala', 16, 'Post-test', 'Macaca_mulatta')
('Amidala', 17, 'Post-test', 'Macaca_mulatta')
('Amidala', 18, 'Post-test', 'Macaca_mulatta')
('Amidala', 19, 'Post-test', 'Macaca_mulatta')
('Amidala', 20, 'Post-test', 'Macaca_mulatta')
('Anyanka', 1, 'Habituation', 'Macaca_mulatta')
('Anyanka', 2, 'Habituation', 'Macaca_mulatta')
('Anyanka', 3, 'Habituation', 'Macaca_mulatta')
('Anyanka', 4, 'Habituation', 'Macaca_mulatta')
('Anyanka', 5, 'Habituation', 'Macaca_mulatta')
('Anyanka', 6, 'Test', 'Macaca_mulatta')
('Anyanka', 7, 'Test', 'Macaca_mulatta')
('Anyanka', 8, 'Test', 'Macaca_mulatta')
('Anyanka', 9, 'Test', 'Macaca_mulatta')
('Anyanka', 10, 'Test', 'Macaca_mulatta')
('Anyanka', 11, 'Test', 'Macaca_mulatta')
('Anyanka', 12, 'Test', 'Macaca_mulatta')
('Anyanka', 13, 'Test', 'Macaca_mulatta')
('Anyanka', 14, 'Test', 'Macaca_mulatta')
('Anyanka', 15, 'Test', 'Macaca_mulatta')
('Anyanka', 16, 'Post-test', 'Macaca_mulatta')
('Anyanka', 17, 'Post-test', 'Macaca_mulatta')
('Anyanka', 18, 'Post-test', 'Macaca_mulatta')
('Anyanka', 19, 'Post-test', 'Macaca_mulatta')
('Anyanka', 20, 'Post-test', 'Macaca_mulatta')
('Arwen', 1, 'Habituation', 'Macaca_mulatta')
('Arwen', 2, 'Habituation', 'Macaca_mulatta')
('Arwen', 3, 'Habituation', 'Macaca_mulatta')
('Arwen', 4, 'Habituation', 'Macaca_mulatta')
('Arwen', 5, 'Habituation', 'Macaca_mulatta')
('Arwen', 6, 'Test', 'Macaca_mulatta')
('Arwen', 7, 'Test', 'Macaca_mulatta')
('Arwen', 8, 'Test', 'Macaca_mulatta')
('Arwen', 9, 'Test', 'Macaca_mulatta')
('Arwen', 10, 'Test', 'Macaca_mulatta')
('Arwen', 11, 'Test', 'Macaca_mulatta')
('Arwen', 12, 'Test', 'Macaca_mulatta')
('Arwen', 13, 'Test', 'Macaca_mulatta')
('Arwen', 14, 'Test', 'Macaca_mulatta')
('Arwen', 15, 'Test', 'Macaca_mulatta')
('Arwen', 16, 'Post-test', 'Macaca_mulatta')
('Arwen', 17, 'Post-test', 'Macaca_mulatta')
('Arwen', 18, 'Post-test', 'Macaca_mulatta')
('Arwen', 19, 'Post-test', 'Macaca_mulatta')
('Arwen', 20, 'Post-test', 'Macaca_mulatta')
('Dory', 1, 'Habituation', 'Macaca_tonkeana')
('Dory', 3, 'Habituation', 'Macaca_tonkeana')
('Dory', 4, 'Habituation', 'Macaca_tonkeana')
('Dory', 5, 'Habituation', 'Macaca_tonkeana')
('Dory', 6, 'Test', 'Macaca_tonkeana')
('Dory', 7, 'Test', 'Macaca_tonkeana')
('Dory', 9, 'Test', 'Macaca_tonkeana')
('Dory', 10, 'Test', 'Macaca_tonkeana')
('Dory', 11, 'Test', 'Macaca_tonkeana')
('Dory', 12, 'Test', 'Macaca_tonkeana')
('Dory', 13, 'Test', 'Macaca_tonkeana')
('Dory', 14, 'Test', 'Macaca_tonkeana')
('Dory', 17, 'Post-test', 'Macaca_tonkeana')
('Dory', 19, 'Post-test', 'Macaca_tonkeana')
('Dory', 20, 'Post-test', 'Macaca_tonkeana')
('Elvise', 1, 'Habituation', 'Macaca_mulatta')
('Elvise', 2, 'Habituation', 'Macaca_mulatta')
('Elvise', 4, 'Habituation', 'Macaca_mulatta')
('Elvise', 5, 'Habituation', 'Macaca_mulatta')
('Elvise', 6, 'Test', 'Macaca_mulatta')
('Elvise', 7, 'Test', 'Macaca_mulatta')
('Elvise', 8, 'Test', 'Macaca_mulatta')
('Elvise', 9, 'Test', 'Macaca_mulatta')
('Elvise', 10, 'Test', 'Macaca_mulatta')
('Elvise', 11, 'Test', 'Macaca_mulatta')
('Elvise', 12, 'Test', 'Macaca_mulatta')
('Elvise', 13, 'Test', 'Macaca_mulatta')
('Elvise', 14, 'Test', 'Macaca_mulatta')
('Elvise', 16, 'Post-test', 'Macaca_mulatta')
('Elvise', 18, 'Post-test', 'Macaca_mulatta')
('Elvise', 19, 'Post-test', 'Macaca_mulatta')
('Elvise', 20, 'Post-test', 'Macaca_mulatta')
('Gabie', 1, 'Habituation', 'Macaca_mulatta')
('Gabie', 2, 'Habituation', 'Macaca_mulatta')
('Gabie', 3, 'Habituation', 'Macaca_mulatta')
('Gabie', 4, 'Habituation', 'Macaca_mulatta')
('Gabie', 5, 'Habituation', 'Macaca_mulatta')
('Gabie', 6, 'Test', 'Macaca_mulatta')
('Gabie', 7, 'Test', 'Macaca_mulatta')
('Gabie', 8, 'Test', 'Macaca_mulatta')
('Gabie', 10, 'Test', 'Macaca_mulatta')
('Gabie', 11, 'Test', 'Macaca_mulatta')
('Gabie', 12, 'Test', 'Macaca_mulatta')
('Gabie', 13, 'Test', 'Macaca_mulatta')
('Gabie', 14, 'Test', 'Macaca_mulatta')
('Gabie', 15, 'Test', 'Macaca_mulatta')
('Gabie', 16, 'Post-test', 'Macaca_mulatta')
('Gabie', 17, 'Post-test', 'Macaca_mulatta')
('Gabie', 18, 'Post-test', 'Macaca_mulatta')
('Gabie', 19, 'Post-test', 'Macaca_mulatta')
('Gabie', 20, 'Post-test', 'Macaca_mulatta')
('Gaia', 1, 'Habituation', 'Macaca_tonkeana')
('Gaia', 2, 'Habituation', 'Macaca_tonkeana')
('Gaia', 3, 'Habituation', 'Macaca_tonkeana')
('Gaia', 6, 'Test', 'Macaca_tonkeana')
('Gaia', 7, 'Test', 'Macaca_tonkeana')
('Gaia', 8, 'Test', 'Macaca_tonkeana')
('Gaia', 9, 'Test', 'Macaca_tonkeana')
('Gaia', 10, 'Test', 'Macaca_tonkeana')
('Gaia', 11, 'Test', 'Macaca_tonkeana')
('Gaia', 12, 'Test', 'Macaca_tonkeana')
('Gaia', 13, 'Test', 'Macaca_tonkeana')
('Gaia', 14, 'Test', 'Macaca_tonkeana')
('Gaia', 15, 'Test', 'Macaca_tonkeana')
('Gaia', 16, 'Post-test', 'Macaca_tonkeana')
('Gaia', 17, 'Post-test', 'Macaca_tonkeana')
('Gaia', 19, 'Post-test', 'Macaca_tonkeana')
('Gaia', 20, 'Post-test', 'Macaca_tonkeana')
('Iron', 1, 'Habituation', 'Macaca_tonkeana')
('Iron', 2, 'Habituation', 'Macaca_tonkeana')
('Iron', 4, 'Habituation', 'Macaca_tonkeana')
('Iron', 7, 'Test', 'Macaca_tonkeana')
('Iron', 8, 'Test', 'Macaca_tonkeana')
('Iron', 9, 'Test', 'Macaca_tonkeana')
('Iron', 10, 'Test', 'Macaca_tonkeana')
('Iron', 11, 'Test', 'Macaca_tonkeana')
('Iron', 12, 'Test', 'Macaca_tonkeana')
('Iron', 13, 'Test', 'Macaca_tonkeana')
('Iron', 14, 'Test', 'Macaca_tonkeana')
('Iron', 16, 'Post-test', 'Macaca_tonkeana')
('Iron', 17, 'Post-test', 'Macaca_tonkeana')
('Iron', 19, 'Post-test', 'Macaca_tonkeana')
('Iron', 20, 'Post-test', 'Macaca_tonkeana')
('Isildur', 3, 'Habituation', 'Macaca_mulatta')
('Isildur', 4, 'Habituation', 'Macaca_mulatta')
('Isildur', 5, 'Habituation', 'Macaca_mulatta')
('Isildur', 6, 'Test', 'Macaca_mulatta')
('Isildur', 7, 'Test', 'Macaca_mulatta')
('Isildur', 8, 'Test', 'Macaca_mulatta')
('Isildur', 9, 'Test', 'Macaca_mulatta')
('Isildur', 10, 'Test', 'Macaca_mulatta')
('Isildur', 11, 'Test', 'Macaca_mulatta')
('Isildur', 12, 'Test', 'Macaca_mulatta')
('Isildur', 13, 'Test', 'Macaca_mulatta')
('Isildur', 14, 'Test', 'Macaca_mulatta')
('Isildur', 15, 'Test', 'Macaca_mulatta')
('Isildur', 16, 'Post-test', 'Macaca_mulatta')
('Isildur', 17, 'Post-test', 'Macaca_mulatta')
('Isildur', 18, 'Post-test', 'Macaca_mulatta')
('Isildur', 20, 'Post-test', 'Macaca_mulatta')
('Natasha', 1, 'Habituation', 'Macaca_mulatta')
('Natasha', 2, 'Habituation', 'Macaca_mulatta')
('Natasha', 3, 'Habituation', 'Macaca_mulatta')
('Natasha', 4, 'Habituation', 'Macaca_mulatta')
('Natasha', 5, 'Habituation', 'Macaca_mulatta')
('Natasha', 6, 'Test', 'Macaca_mulatta')
('Natasha', 7, 'Test', 'Macaca_mulatta')
('Natasha', 8, 'Test', 'Macaca_mulatta')
('Natasha', 11, 'Test', 'Macaca_mulatta')
('Natasha', 13, 'Test', 'Macaca_mulatta')
('Natasha', 14, 'Test', 'Macaca_mulatta')
('Natasha', 15, 'Test', 'Macaca_mulatta')
('Natasha', 17, 'Post-test', 'Macaca_mulatta')
('Natasha', 18, 'Post-test', 'Macaca_mulatta')
('Natasha', 19, 'Post-test', 'Macaca_mulatta')
('Natasha', 20, 'Post-test', 'Macaca_mulatta')
('Nereis', 2, 'Habituation', 'Macaca_tonkeana')
('Nereis', 3, 'Habituation', 'Macaca_tonkeana')
('Nereis', 4, 'Habituation', 'Macaca_tonkeana')
('Nereis', 5, 'Habituation', 'Macaca_tonkeana')
('Nereis', 6, 'Test', 'Macaca_tonkeana')
('Nereis', 7, 'Test', 'Macaca_tonkeana')
('Nereis', 8, 'Test', 'Macaca_tonkeana')
('Nereis', 9, 'Test', 'Macaca_tonkeana')
('Nereis', 10, 'Test', 'Macaca_tonkeana')
('Nereis', 11, 'Test', 'Macaca_tonkeana')
('Nereis', 12, 'Test', 'Macaca_tonkeana')
('Nereis', 13, 'Test', 'Macaca_tonkeana')
('Nereis', 14, 'Test', 'Macaca_tonkeana')
('Nereis', 15, 'Test', 'Macaca_tonkeana')
('Nereis', 16, 'Post-test', 'Macaca_tonkeana')
('Nereis', 17, 'Post-test', 'Macaca_tonkeana')
('Nereis', 18, 'Post-test', 'Macaca_tonkeana')
('Nereis', 19, 'Post-test', 'Macaca_tonkeana')
('Nereis', 20, 'Post-test', 'Macaca_tonkeana')
('Rambo', 1, 'Habituation', 'Macaca_mulatta')
('Rambo', 3, 'Habituation', 'Macaca_mulatta')
('Rambo', 4, 'Habituation', 'Macaca_mulatta')
('Rambo', 5, 'Habituation', 'Macaca_mulatta')
('Rambo', 6, 'Test', 'Macaca_mulatta')
('Rambo', 7, 'Test', 'Macaca_mulatta')
('Rambo', 8, 'Test', 'Macaca_mulatta')
('Rambo', 10, 'Test', 'Macaca_mulatta')
('Rambo', 11, 'Test', 'Macaca_mulatta')
('Rambo', 12, 'Test', 'Macaca_mulatta')
('Rambo', 13, 'Test', 'Macaca_mulatta')
('Rambo', 14, 'Test', 'Macaca_mulatta')
('Rambo', 15, 'Test', 'Macaca_mulatta')
('Rambo', 16, 'Post-test', 'Macaca_mulatta')
('Rambo', 17, 'Post-test', 'Macaca_mulatta')

('Rambo', 18, 'Post-test', 'Macaca_mulatta')
('Rambo', 19, 'Post-test', 'Macaca_mulatta')
('Rambo', 20, 'Post-test', 'Macaca_mulatta')
('Yannick', 1, 'Habituation', 'Macaca_tonkeana')
('Yannick', 2, 'Habituation', 'Macaca_tonkeana')
('Yannick', 3, 'Habituation', 'Macaca_tonkeana')
('Yannick', 4, 'Habituation', 'Macaca_tonkeana')
('Yannick', 5, 'Habituation', 'Macaca_tonkeana')
('Yannick', 6, 'Test', 'Macaca_tonkeana')
('Yannick', 7, 'Test', 'Macaca_tonkeana')
('Yannick', 8, 'Test', 'Macaca_tonkeana')
('Yannick', 9, 'Test', 'Macaca_tonkeana')
('Yannick', 10, 'Test', 'Macaca_tonkeana')
('Yannick', 11, 'Test', 'Macaca_tonkeana')
('Yannick', 12, 'Test', 'Macaca_tonkeana')
('Yannick', 13, 'Test', 'Macaca_tonkeana')
('Yannick', 14, 'Test', 'Macaca_tonkeana')
('Yannick', 15, 'Test', 'Macaca_tonkeana')
('Yannick', 16, 'Post-test', 'Macaca_tonkeana')
('Yannick', 17, 'Post-test', 'Macaca_tonkeana')
('Yannick', 18, 'Post-test', 'Macaca_tonkeana')
('Yannick', 19, 'Post-test', 'Macaca_tonkeana')
('Yannick', 20, 'Post-test', 'Macaca_tonkeana')
('Yin', 1, 'Habituation', 'Macaca_tonkeana')
('Yin', 2, 'Habituation', 'Macaca_tonkeana')
('Yin', 3, 'Habituation', 'Macaca_tonkeana')
('Yin', 4, 'Habituation', 'Macaca_tonkeana')
('Yin', 5, 'Habituation', 'Macaca_tonkeana')
('Yin', 6, 'Test', 'Macaca_tonkeana')
('Yin', 7, 'Test', 'Macaca_tonkeana')
('Yin', 8, 'Test', 'Macaca_tonkeana')
('Yin', 9, 'Test', 'Macaca_tonkeana')
('Yin', 10, 'Test', 'Macaca_tonkeana')
('Yin', 11, 'Test', 'Macaca_tonkeana')
('Yin', 12, 'Test', 'Macaca_tonkeana')
('Yin', 13, 'Test', 'Macaca_tonkeana')
('Yin', 14, 'Test', 'Macaca_tonkeana')
('Yin', 15, 'Test', 'Macaca_tonkeana')
('Yin', 16, 'Post-test', 'Macaca_tonkeana')
('Yin', 17, 'Post-test', 'Macaca_tonkeana')
('Yin', 19, 'Post-test', 'Macaca_tonkeana')
('Yin', 20, 'Post-test', 'Macaca_tonkeana')

In [72]:
temp

,Behavior,Phase_Session,Rows,Cols,Reward,Time,PST_condition,Subject,Session,Phase,Species
0,D5,5,4,3,1,5.32,Transparent,Yin,20,Post-test,Macaca_tonkeana
1,E4,5,3,4,1,7.30,Transparent,Yin,20,Post-test,Macaca_tonkeana
2,D4,5,3,3,1,10.16,Transparent,Yin,20,Post-test,Macaca_tonkeana
3,C4,5,3,2,1,14.06,Transparent,Yin,20,Post-test,Macaca_tonkeana
4,C5,5,4,2,1,15.92,Transparent,Yin,20,Post-test,Macaca_tonkeana
5,B5,5,4,1,1,17.32,Transparent,Yin,20,Post-test,Macaca_tonkeana
6,A5,5,4,0,1,20.02,Transparent,Yin,20,Post-test,Macaca_tonkeana
7,B2,5,1,1,1,20.92,Transparent,Yin,20,Post-test,Macaca_tonkeana
8,A2,5,1,0,1,22.76,Transparent,Yin,20,Post-test,Macaca_tonkeana
9,A3,5,2,0,1,25.20,Transparent,Yin,20,Post-test,Macaca_tonkeana
10,B3,5,2,1,1,26.44,Transparent,Yin,20,Post-test,Macaca_tonkeana
11,D3,5,2,3,1,28.94,Transparent,Yin,20,Post-test,Macaca_tonkeana
12,E3,5,2,4,1,29.96,Transparent,Yin,20,Post-test,Macaca_tonkeana
13,D1,5,0,3,1,31.62,Transparent,Yin,20,Post-test,Macaca_tonkeana
14,E1,5,0,4,1,32.78,Transparent,Yin,20,Post-test,Macaca_tonkeana
15,C1,5,0,2,1,34.76,Transparent,Yin,20,Post-test,Macaca_tonkeana
16,B1,5,0,1,1,36.36,Transparent,Yin,20,Post-test,Macaca_tonkeana
17,C3,5,2,2,1,38.50,Transparent,Yin,20,Post-test,Macaca_tonkeana
18,B4,5,3,1,1,40.22,Transparent,Yin,20,Post-test,Macaca_tonkeana
19,D5,5,4,3,0,41.74,Transparent,Yin,20,Post-test,Macaca_tonkeana

In [70]:
processed_data

,Behavior,Rows,Cols,Reward,Time,PST_condition,Subject,Session,Phase,Species
0,D2,1,3,1,13.28,Transparent,Amidala,1,Habituation,Macaca_mulatta
1,E3,2,4,1,17.32,Transparent,Amidala,1,Habituation,Macaca_mulatta
2,E2,1,4,1,20.88,Transparent,Amidala,1,Habituation,Macaca_mulatta
3,D5,4,3,1,25.24,Transparent,Amidala,1,Habituation,Macaca_mulatta
4,C5,4,2,1,29.20,Transparent,Amidala,1,Habituation,Macaca_mulatta
...,...,...,...,...,...,...,...,...,...,...
15,C1,0,2,1,34.76,Transparent,Yin,20,Post-test,Macaca_tonkeana
16,B1,0,1,1,36.36,Transparent,Yin,20,Post-test,Macaca_tonkeana
17,C3,2,2,1,38.50,Transparent,Yin,20,Post-test,Macaca_tonkeana
18,B4,3,1,1,40.22,Transparent,Yin,20,Post-test,Macaca_tonkeana
19,D5,4,3,0,41.74,Transparent,Yin,20,Post-test,Macaca_tonkeana

In [64]:
processed_data.to_csv(data_dir+"extracted_trajs.csv")

In [60]:
np.array(coords)[:,0].flatten()

array([4, 3, 3, 3, 4, 4, 4, 1, 1, 2, 2, 2, 2, 0, 0, 0, 0, 2, 3, 4])

In [61]:
sub

,Observation id,Subject,Species,Session,Phase,Phase_session,PST condition,Behavior,Modifier #1,Observation date,Observation duration,Observation type,Media duration (s),coder,Date,Behavioral category,Modifier #2,Behavior type,Time
5934,YIN_20-03-2026_2,Yin,Macaca_tonkeana,20,Post-test,5,Transparent,D5,Success,2026-05-04 00:20:48.148,62.06,Media file(s),97.92,Francis,20.03.2026,PST,NaN,POINT,5.32
5935,YIN_20-03-2026_2,Yin,Macaca_tonkeana,20,Post-test,5,Transparent,E4,Success,2026-05-04 00:20:48.148,62.06,Media file(s),97.92,Francis,20.03.2026,PST,NaN,POINT,7.30
5938,YIN_20-03-2026_2,Yin,Macaca_tonkeana,20,Post-test,5,Transparent,D4,Success,2026-05-04 00:20:48.148,62.06,Media file(s),97.92,Francis,20.03.2026,PST,NaN,POINT,10.16
5940,YIN_20-03-2026_2,Yin,Macaca_tonkeana,20,Post-test,5,Transparent,C4,Success,2026-05-04 00:20:48.148,62.06,Media file(s),97.92,Francis,20.03.2026,PST,NaN,POINT,14.06
5941,YIN_20-03-2026_2,Yin,Macaca_tonkeana,20,Post-test,5,Transparent,C5,Success,2026-05-04 00:20:48.148,62.06,Media file(s),97.92,Francis,20.03.2026,PST,NaN,POINT,15.92
5942,YIN_20-03-2026_2,Yin,Macaca_tonkeana,20,Post-test,5,Transparent,B5,Success,2026-05-04 00:20:48.148,62.06,Media file(s),97.92,Francis,20.03.2026,PST,NaN,POINT,17.32
5943,YIN_20-03-2026_2,Yin,Macaca_tonkeana,20,Post-test,5,Transparent,A5,Success,2026-05-04 00:20:48.148,62.06,Media file(s),97.92,Francis,20.03.2026,PST,NaN,POINT,20.02
5944,YIN_20-03-2026_2,Yin,Macaca_tonkeana,20,Post-test,5,Transparent,B2,Success,2026-05-04 00:20:48.148,62.06,Media file(s),97.92,Francis,20.03.2026,PST,NaN,POINT,20.92
5945,YIN_20-03-2026_2,Yin,Macaca_tonkeana,20,Post-test,5,Transparent,A2,Success,2026-05-04 00:20:48.148,62.06,Media file(s),97.92,Francis,20.03.2026,PST,NaN,POINT,22.76
5946,YIN_20-03-2026_2,Yin,Macaca_tonkeana,20,Post-test,5,Transparent,A3,Success,2026-05-04 00:20:48.148,62.06,Media file(s),97.92,Francis,20.03.2026,PST,NaN,POINT,25.20
5947,YIN_20-03-2026_2,Yin,Macaca_tonkeana,20,Post-test,5,Transparent,B3,Success,2026-05-04 00:20:48.148,62.06,Media file(s),97.92,Francis,20.03.2026,PST,NaN,POINT,26.44
5948,YIN_20-03-2026_2,Yin,Macaca_tonkeana,20,Post-test,5,Transparent,D3,Success,2026-05-04 00:20:48.148,62.06,Media file(s),97.92,Francis,20.03.2026,PST,NaN,POINT,28.94
5949,YIN_20-03-2026_2,Yin,Macaca_tonkeana,20,Post-test,5,Transparent,E3,Success,2026-05-04 00:20:48.148,62.06,Media file(s),97.92,Francis,20.03.2026,PST,NaN,POINT,29.96
5950,YIN_20-03-2026_2,Yin,Macaca_tonkeana,20,Post-test,5,Transparent,D1,Success,2026-05-04 00:20:48.148,62.06,Media file(s),97.92,Francis,20.03.2026,PST,NaN,POINT,31.62
5951,YIN_20-03-2026_2,Yin,Macaca_tonkeana,20,Post-test,5,Transparent,E1,Success,2026-05-04 00:20:48.148,62.06,Media file(s),97.92,Francis,20.03.2026,PST,NaN,POINT,32.78
5952,YIN_20-03-2026_2,Yin,Macaca_tonkeana,20,Post-test,5,Transparent,C1,Success,2026-05-04 00:20:48.148,62.06,Media file(s),97.92,Francis,20.03.2026,PST,NaN,POINT,34.76
5953,YIN_20-03-2026_2,Yin,Macaca_tonkeana,20,Post-test,5,Transparent,B1,Success,2026-05-04 00:20:48.148,62.06,Media file(s),97.92,Francis,20.03.2026,PST,NaN,POINT,36.36
5954,YIN_20-03-2026_2,Yin,Macaca_tonkeana,20,Post-test,5,Transparent,C3,Success,2026-05-04 00:20:48.148,62.06,Media file(s),97.92,Francis,20.03.2026,PST,NaN,POINT,38.50
5955,YIN_20-03-2026_2,Yin,Macaca_tonkeana,20,Post-test,5,Transparent,B4,Success,2026-05-04 00:20:48.148,62.06,Media file(s),97.92,Francis,20.03.2026,PST,NaN,POINT,40.22
5956,YIN_20-03-2026_2,Yin,Macaca_tonkeana,20,Post-test,5,Transparent,D5,Revisit,2026-05-04 00:20:48.148,62.06,Media file(s),97.92,Francis,20.03.2026,PST,NaN,POINT,41.74

In [14]:
sub['Behavior']

5934    D5
5935    E4
5938    D4
5940    C4
5941    C5
5942    B5
5943    A5
5944    B2
5945    A2
5946    A3
5947    B3
5948    D3
5949    E3
5950    D1
5951    E1
5952    C1
5953    B1
5954    C3
5955    B4
Name: Behavior, dtype: object